import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1
 */
public class cstlog extends javax.swing.JFrame {

    /**
     * Creates new form cstlog
     */
    public cstlog() {
        initComponents();
             }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        p = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(t1);
        t1.setBounds(270, 80, 230, 50);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.PNG"))); // NOI18N
        l1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1);
        l1.setBounds(420, 170, 60, 50);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hide1.png"))); // NOI18N
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        getContentPane().add(l2);
        l2.setBounds(420, 170, 60, 50);
        getContentPane().add(p);
        p.setBounds(270, 170, 220, 50);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Enter Account No");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 80, 210, 50);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Enter Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 170, 210, 50);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 310, 105, 36);

        jButton2.setText("If you don't have account please click here to sign up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 370, 355, 35);

        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 260, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/bms", "root","f1*j#7$Q9");
            Statement stmt = con.createStatement();
            String qr = "Select Password from account where Account_no = "+t1.getText()+";";
            ResultSet rs = stmt.executeQuery(qr);
         if(rs.next())
            {
                String pw = rs.getString(1);
                String pwd = new String(p.getPassword());
                if(pw.equals(pwd))
                {
                    //pay_open po = new pay_open();
                    new  singed_up().setVisible(true);
                    this.setVisible(false);
                }
                else
                JOptionPane.showMessageDialog(null,"Enter Correct Password");
            }
            
            else
            JOptionPane.showMessageDialog(null,"Incorrect Account No");

    }
    catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    /*        //PreparedStatement ps = con.prepareStatement("Select * from cl where Account_no = "+t1.getText()+",Password = '"+ new String(p.getPassword()+"';"));
         PreparedStatement ps = con.prepareStatement("select * from cl where acoount_no =?,password=?");
                ps.setString(1,t1.getText());
                ps.setString(2,new String(p.getPassword()));
                    ResultSet rs1=ps.executeQuery();
                   if(rs1.next())
                   {
                    JOptionPane.showMessageDialog(this,"Login Successfully");
                    new openaccount().setVisible(true);
                    this.setVisible(false);
                    openaccount.t11.setText(""+rs1.getString("a/cno"));
                    openaccount.t1.setText(""+rs1.getString("Name"));
                    openaccount.t2.setText(""+rs1.getString("DOB"));
                    openaccount.t3.setText(""+rs1.getString("Mobile"));
                    openaccount.t10.setText(""+rs1.getString("Date"));
                    openaccount.t12.setText(""+rs1.getString("Time"));
                    openaccount.t4.setText(""+rs1.getString("Age"));
                    openaccount.t5.setText(""+rs1.getString("email"));
                    openaccount.t6.setText(""+rs1.getString("Gender"));
                    openaccount.t7.setText(""+rs1.getString("Add"));
                    openaccount.t8.setText(""+rs1.getString("Pswrd"));
                       }                 
               
           */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cstsu cs = new cstsu();
        cs.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        p.setEchoChar((char)0);
        l1.setVisible(false);
        l2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
     
     p.setEchoChar('*');
     l2.setVisible(false);
     l1.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/bms", "root", "f1*j#7$Q9");
        Statement stmt = con.createStatement();
        String qr = "Select password from account where account_no = "+t1.getText();
        ResultSet rs = stmt.executeQuery(qr);
        if (rs.next()){
            String pw = rs.getString(1);
            String psw = new String(p.getPassword());
            if (pw.equals(psw)){
                new singed_up().setVisible(true);
                this.setVisible(false);
            }
        }
        
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cstlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cstlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cstlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cstlog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cstlog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    public static javax.swing.JPasswordField p;
    public static javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
