import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1
 */
public class mngrr extends javax.swing.JFrame {

    /**
     * Creates new form mngrr
     */
    public mngrr() {
        initComponents();
   // auto_no();                     - You can also make the method named auto_no which is maked just below in comments...
     try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/bms","root","");
            Statement stmt = con.createStatement();
            String qr = "Select Account_no,name,date,age,password from account order by Date";
            ResultSet rs = stmt.executeQuery(qr);
            while(rs.next())
            {
              String a =rs.getString(1);
              String b =rs.getString(2);
              String c =rs.getString(3);
              String d =rs.getString(4);
              String e =rs.getString(5);
              DefaultTableModel dtm = (DefaultTableModel)t.getModel();
              dtm.addRow(new Object[] {a,b,c,d,e} );
                  }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
  /*  public void auto_no()
    {
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/bms","root","");
            Statement stmt = con.createStatement();
            String qr = "Select Account_no,name,date,age,password from account order by Date";
            ResultSet rs = stmt.executeQuery(qr);
            while(rs.next())
            {
              String a =rs.getString(1);
              String b =rs.getString(2);
              String c =rs.getString(3);
              String d =rs.getString(4);
              String e =rs.getString(5);
              DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
              dtm.addRow(new Object[] {a,b,c,d,e} );
                }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No", "Name", "Date", "Age", "Password"
            }
        ));
        jScrollPane1.setViewportView(t);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int ans = JOptionPane.showConfirmDialog(null,"Confirm to delete account");
        if(ans==JOptionPane.YES_OPTION){
            try{
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/bms","root","");
                Statement stmt = con.createStatement();
                int a = t.getSelectedRow();
                TableModel tm = t.getModel();
                String acno = (String)tm.getValueAt(a,0);
                String qr = "Delete from account where account_no ="+acno+";";
                stmt.executeUpdate(qr);
               DefaultTableModel dtm = (DefaultTableModel)t.getModel();
               dtm.removeRow(a);
               JOptionPane.showMessageDialog(this,"Data Successfully Deleted");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/bms","root","");
        Statement stmt = con.createStatement();
        DefaultTableModel dtm = (DefaultTableModel)t.getModel();
        String acno=(String) dtm.getValueAt(t.getSelectedRow(),0);
        String qr = "Select * from account where account_no="+acno+";";
        ResultSet rs = stmt.executeQuery(qr);
        if(rs.next()){
         new mngropenaccount().setVisible(true);
        this.setVisible(false);
        mngropenaccount.t11.setText(""+rs.getString(1));
        mngropenaccount.t1.setText(""+rs.getString("Name"));
        mngropenaccount.t2.setText(""+rs.getString("DOB"));
        mngropenaccount.t3.setText(""+rs.getString("Mobile"));
        mngropenaccount.t10.setText(""+rs.getString("Date"));
        mngropenaccount.t12.setText(""+rs.getString("Time"));
        mngropenaccount.t4.setText(""+rs.getString("Age"));
        mngropenaccount.t5.setText(""+rs.getString("email"));
        mngropenaccount.t6.setText(""+rs.getString("Gender"));
        mngropenaccount.t7.setText(""+rs.getString("Address"));
        mngropenaccount.t8.setText(""+rs.getString("Password"));    
         }
    }
       catch(Exception e){
               JOptionPane.showMessageDialog(null, e);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mngrr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mngrr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mngrr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mngrr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mngrr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t;
    // End of variables declaration//GEN-END:variables
}
